<?php

function microservice_menu() {
  $items['microservice/news'] = array(
    'page callback' => 'microservice_page_callback',
    'access callback' => TRUE,
    'title' => t('News Microservice'),
    'cache' => FALSE
  );
  $items['microservice/news/%'] = array(
    'page callback' => 'microservice_page_callback',
    'access callback' => TRUE,
    'title' => t('News Microservice'),
    'page arguments' => array(2),
    'cache' => FALSE
  );
  return $items;
}

function microservice_page_callback($tag = NULL) {
  if ($tag == NULL) {
    $_tag = 'drupal';
  }
  else {
    $_tag = $tag;
  }
  $articles = _microservice_get_articles($_tag);
  $return = '<h1>Latest news for: ' . $_tag . '</h1>';
  $return .= '<ul>';
  foreach($articles as $article) {
    $return .= '<li>';
    if ($article->url) {
      $return .= '<a href="' . $article->url . '">';
    }
    $return .= (isset($article->title) ? $article->title : 'no name');
    if ($article->url) {
      $return .= '</a>';
    }
    $return .= '</li>';
  }
  $return .= '</ul>';
  $return .= 'Go to: <a href="/microservice/news/bitcoin">bitcoin</a> | <a href="/microservice/news/docker">docker</a> | <a href="/microservice/news/microservices">microservices</a>';
  return $return;
}

function _microservice_get_articles($tag) {
  $req = drupal_http_request('http://microservice:4000/graphql', array('method' => 'POST', 'data' => '{"query":"query {\n\tnews(tag: \"'.$tag.'\") {\n    author\n    title\n    description\n    url\n    urlToImage\n    publishedAt\n    content\n    source {\n      id\n      name\n    }\n  }\n}"}', 'headers' => array('Content-Type' => 'application/json', 'Accept' => 'application/json')));
  if ($req) {
    if ($req->status_message == 'OK') {
      if ($req->data) {
        $data = json_decode($req->data);
        if ($data->data && $data->data->news) {
          $articles = $data->data->news;
        }
      }
    }
    return $articles;
  }
  return NULL;
}